// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	login "github.com/SIN5t/CancerCellDetectSys/cmd/api/biz/router/login"
	upload "github.com/SIN5t/CancerCellDetectSys/cmd/api/biz/router/upload"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	login.Register(r)

	upload.Register(r)
}
