// Code generated by hertz generator.

package login

import (
	"context"

	login "github.com/SIN5t/CancerCellDetectSys/cmd/api/biz/model/login"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Login .
// @router ccds/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req login.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	if req.Password == "123456" && req.Username == "admin" {
		c.JSON(consts.StatusOK, login.LoginResponse{
			Code:    consts.StatusOK,
			Message: "成功登入",

			Data: &login.Data{
				Token: "123456789",
			},
		})
	} else {
		c.JSON(consts.StatusOK, login.LoginResponse{
			Code:    400,
			Message: "用户名或密码错误",
			Data:    nil,
		})

			Data:    &login.Data{
				//Token: "123456789",
			},
		})
	} 
}
