// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func main() {

	h := server.New(
		server.WithHostPorts(":8888"),
		server.WithMaxRequestBodySize(1024*1024*1024*5), //最大请求体大小
	)
	hlog.SetLevel(hlog.LevelInfo)
	register(h)
	h.Spin()
}
