// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func main() {

	h := server.Default()
	hlog.SetLevel(hlog.LevelInfo)
	register(h)
	h.Spin()
}
