// Code generated by hertz generator.

package login

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	/*return []app.HandlerFunc{
		cors.InitCors(),
	}*/
	return nil
}

func _ccdsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}
